name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  path_provider: ^1.6.1
  path_provider_macos: ^0.0.3+1
  audioplayers: ^0.14.0
    # path: ../
  provider: ^4.0.4
flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
